### ISSUE TITLE
Proper versionning

### ISSUE THREAD

**Issue by noirbizarre** [zakird/celerybeat-mongo#12]
Hi !

Right now, there is a new 0.0.10 that has been published, but it doesn't seems retrocompatible and we don't know what's in it.

As a consequence, it's very difficult to properly upgrade.
Is it possible to provide a changelog for versionning and to tag published version ?

**Comment by zakird** [comment]
Yeah, that's fair. Didn't realize others were deploying this in production. 0.0.10 shouldn't have broken backwards compatibility. Any information on what happened there?

**Comment by noirbizarre** [comment]
Switching from Document to DynamicDocument as base class breaks my app.

It may be specific to my use case.
I'm investigating why right now and will give more details as soon as I have them.

**Comment by zakird** [comment]
Interesting, alright. I apologize for that---I did not expect that change to break other code, given that it just means that you can set and read back additional fields on the object.

**Comment by zakird** [comment]
Do you get this resolved?

**Comment by noirbizarre** [comment]
Sorry for the lack of response.

The problem is on MongoEngine side and I have a pull-request soon to bee proposed to fix the issue.

Thanks anyway.
