### ISSUE TITLE
Feature request: The ability to set UPDATE_INTERVAL via the config file

### ISSUE THREAD

**Issue by jemilsson** [zakird/celerybeat-mongo#13]
I am having issues with the short update interval. I have a large schedule and the celery beat process is spending much of its time synching the schedule. It would be great if it was possible setting the update interval in the config file. I suppose it is possible changing the interval manually, but it would be neat if it was possible through the config file.

**Comment by zakird** [comment]
I believe this can be defined by setting CELERYBEAT_MAX_LOOP_INTERVAL.

**Comment by zakird** [comment]
I'm closing since this has gone unresponded to for 6 months and it isn't clear that there's anything to be fixed within the library.
