### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by zanpen2000** [zakird/celerybeat-mongo#15]
{
    "_id" : ObjectId("55e411d549054883cea9b5d7"),
    "name" : "tt",
    "task" : "tasks.test",
    "enabled" : true,
    "crontab" : {
        "minute" : "1",
        "hour" : "*",
        "day_of_week" : "*",
        "day_of_month" : "*",
        "month_of_year" : "*"
    },
    "args" : [ 
        
    ],
    "kwargs" : {},
    "total_run_count" : 5
}

config file:
https://github.com/zanpen2000/celerybeat-test/blob/master/celeryconfig.py

tasks.py
https://github.com/zanpen2000/celerybeat-test/blob/master/tasks.py

Please ! Thank YOU !

**Comment by ThrowsException** [comment]
You have to create the task using monoengine with the provided models in `celerybeatmongo.models`. The code that finds the tasks to run uses mongoengine to perform its query so if it doesn't have the necessary attributes that mongoengine recognizes it does not get picked up in the query. I just wrote a short script that imports `celerybeatmongo.models` and inserts a task.

**Comment by zanpen2000** [comment]
Is there example code for me ? I still can't understand ...

**Comment by zanpen2000** [comment]
hey bro, would you give me some sample code please ? thanks!

2015-08-31 20:16 GMT+08:00 ThrowsException <notifications@github.com>:

**Comment by zanpen2000** [comment]
this is my code:

[image: 内嵌图片 1]

2015-09-01 10:13 GMT+08:00 pong Chong <zanpen2000@gmail.com>:

**Comment by zakird** [comment]
This looks like the same problem where there aren't the necessary MongoEngine attributes. This is annoying and is kind of a bug that was introduced when the model became inheritable (before that the class attribute wasn't needed). Will change in the readme.

**Comment by zanpen2000** [comment]
IT WORKS!
Thank you for your time, thank you very mush, It's a big HELP! 

Have a nice day :+1:
