### ISSUE TITLE
Celery beat is not working with MongoScheduler

### ISSUE THREAD

**Issue by kamilali** [zakird/celerybeat-mongo#75]
We run celery beat and celery worker. We use PeriodicTask correctly and save stores it the schedules collection in our db. But celery beat does not pick up the task and add to queue for worker to process on the scheduled time. It used to work for us but all of a sudden it has stopped working. So we know our task configuration is correct since it used to work. Any guidance here?

We are running the following commands:

celery --app app.celery beat -S celerybeatmongo.schedulers.MongoScheduler --loglevel=debug
celery --app app.celery worker --loglevel=debug

The logs only show:

[2023-01-09 09:23:43,294: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2023-01-09 09:23:48,697: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2023-01-09 09:23:54,087: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.
[2023-01-09 09:24:00,893: DEBUG/MainProcess] beat: Waking up in 5.00 seconds.

They don't show the task being picked up despite it being in the db.

The task configuration is as follows in the db:

{
_id: ObjectId('63a38122893af0ab7af4832a'),
_cls: "PeriodicTask",
name: "test-task",
task: "scheduler.tasks.test_func",
crontab: Object,
args: Array,
kwargs: Object,
expires: 2023-12-22T18:05:00.000+00:00,
enabled: true
total_run_count: 0
max_run_count: 0
run_immediately: false
last_run_at: <some time>
}

Would appreciate any help here. Seem like an issue with how beat and the MongoScheduler interface with one another.

**Comment by Knight1997** [comment]
@kamilali I am facing same issue, any pointers how did you resolve this?
